version: "2"
services:

  referencedata:
    image: openlmis/referencedata
    env_file: .env
    depends_on: [db, log, redis]

  db:
    image: openlmis/postgres:12-debezium
    ports:
      - "5432"
    env_file: .env

  redis:
    image: redis:3.2.12
    ports:
      - "6379"
    depends_on: [log]

  log:
    image: openlmis/rsyslog:3
    ports:
      - "514"
      - "12514:514/udp"
    volumes:
      - '../logs/referencedata:/var/log'
